github_actions:
  - .github/**/*

questions game:
  - src/pages/questions/**/*

logo game:
  - src/pages/logos/**/*,
  - src/components/LogoForm.jsx,
  - src/pages/logos/LogoAnnotation.jsx
  - src/pages/logos/LogoDeepSearch.jsx

insights:
  - src/pages/insights/**/*

eco-score game:
  - src/pages/eco-score/**/*

i18n:
  - src/i18n/**/*

Nutrition game:
  - src/pages/nutrition/**/*
  - src/pages/nutrition/index.jsx
